# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T12:22:33+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, confloat, conint, constr


class AccessDeniedException(RootModel[Any]):
    root: Any


class AliasName(
    RootModel[constr(pattern=r'^([A-Za-z]_?)+$', min_length=1, max_length=100)]
):
    root: constr(pattern=r'^([A-Za-z]_?)+$', min_length=1, max_length=100)


class AliasNameOrListAll(
    RootModel[constr(pattern=r'^(-|^([A-Za-z]_?)+$)$', min_length=1, max_length=100)]
):
    root: constr(pattern=r'^(-|^([A-Za-z]_?)+$)$', min_length=1, max_length=100)


class AmazonResourceName(RootModel[constr(min_length=1, max_length=1011)]):
    root: constr(min_length=1, max_length=1011)


class BadRequestException(RootModel[Any]):
    root: Any


class Blob(RootModel[str]):
    root: str


class Boolean(RootModel[bool]):
    root: bool


class BotChannelName(
    RootModel[constr(pattern=r'^([A-Za-z]_?)+$', min_length=1, max_length=100)]
):
    root: constr(pattern=r'^([A-Za-z]_?)+$', min_length=1, max_length=100)


class BotName(
    RootModel[constr(pattern=r'^([A-Za-z]_?)+$', min_length=2, max_length=50)]
):
    root: constr(pattern=r'^([A-Za-z]_?)+$', min_length=2, max_length=50)


class BuiltinIntentSignature(RootModel[str]):
    root: str


class BuiltinSlotTypeSignature(RootModel[str]):
    root: str


class ChannelStatus(Enum):
    IN_PROGRESS = 'IN_PROGRESS'
    CREATED = 'CREATED'
    FAILED = 'FAILED'


class ChannelType(Enum):
    Facebook = 'Facebook'
    Slack = 'Slack'
    Twilio_Sms = 'Twilio-Sms'
    Kik = 'Kik'


class ConfidenceThreshold(RootModel[confloat(ge=0.0, le=1.0)]):
    root: confloat(ge=0.0, le=1.0)


class ConflictException(RootModel[Any]):
    root: Any


class ContentString(RootModel[constr(min_length=1, max_length=1000)]):
    root: constr(min_length=1, max_length=1000)


class ContentType(Enum):
    PlainText = 'PlainText'
    SSML = 'SSML'
    CustomPayload = 'CustomPayload'


class ContextTimeToLiveInSeconds(RootModel[conint(ge=5, le=86400)]):
    root: conint(ge=5, le=86400)


class ContextTurnsToLive(RootModel[conint(ge=1, le=20)]):
    root: conint(ge=1, le=20)


class Count(RootModel[int]):
    root: int


class CustomOrBuiltinSlotTypeName(
    RootModel[
        constr(pattern=r'^((AMAZON\.)_?|[A-Za-z]_?)+', min_length=1, max_length=100)
    ]
):
    root: constr(pattern=r'^((AMAZON\.)_?|[A-Za-z]_?)+', min_length=1, max_length=100)


class DeleteBotAliasRequest(BaseModel):
    pass


class DeleteBotChannelAssociationRequest(BaseModel):
    pass


class DeleteBotRequest(BaseModel):
    pass


class DeleteBotVersionRequest(BaseModel):
    pass


class DeleteIntentRequest(BaseModel):
    pass


class DeleteIntentVersionRequest(BaseModel):
    pass


class DeleteSlotTypeRequest(BaseModel):
    pass


class DeleteSlotTypeVersionRequest(BaseModel):
    pass


class DeleteUtterancesRequest(BaseModel):
    pass


class Description(RootModel[constr(min_length=0, max_length=200)]):
    root: constr(min_length=0, max_length=200)


class Destination(Enum):
    CLOUDWATCH_LOGS = 'CLOUDWATCH_LOGS'
    S3 = 'S3'


class ExportStatus(Enum):
    IN_PROGRESS = 'IN_PROGRESS'
    READY = 'READY'
    FAILED = 'FAILED'


class ExportType(Enum):
    ALEXA_SKILLS_KIT = 'ALEXA_SKILLS_KIT'
    LEX = 'LEX'


class FulfillmentActivityType(Enum):
    ReturnIntent = 'ReturnIntent'
    CodeHook = 'CodeHook'


class GetBotAliasRequest(BaseModel):
    pass


class GetBotAliasesRequest(BaseModel):
    pass


class GetBotChannelAssociationRequest(BaseModel):
    pass


class GetBotChannelAssociationsRequest(BaseModel):
    pass


class GetBotRequest(BaseModel):
    pass


class GetBotVersionsRequest(BaseModel):
    pass


class GetBotsRequest(BaseModel):
    pass


class GetBuiltinIntentRequest(BaseModel):
    pass


class GetBuiltinIntentsRequest(BaseModel):
    pass


class GetBuiltinSlotTypesRequest(BaseModel):
    pass


class GetExportRequest(BaseModel):
    pass


class GetImportRequest(BaseModel):
    pass


class GetIntentRequest(BaseModel):
    pass


class GetIntentVersionsRequest(BaseModel):
    pass


class GetIntentsRequest(BaseModel):
    pass


class GetMigrationRequest(BaseModel):
    pass


class GetMigrationsRequest(BaseModel):
    pass


class GetSlotTypeRequest(BaseModel):
    pass


class GetSlotTypeVersionsRequest(BaseModel):
    pass


class GetSlotTypesRequest(BaseModel):
    pass


class GetUtterancesViewRequest(BaseModel):
    pass


class GroupNumber(RootModel[conint(ge=1, le=5)]):
    root: conint(ge=1, le=5)


class IamRoleArn(
    RootModel[
        constr(
            pattern=r'^arn:[\w\-]+:iam::[\d]{12}:role/.+$',
            min_length=20,
            max_length=2048,
        )
    ]
):
    root: constr(
        pattern=r'^arn:[\w\-]+:iam::[\d]{12}:role/.+$', min_length=20, max_length=2048
    )


class ImportStatus(Enum):
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETE = 'COMPLETE'
    FAILED = 'FAILED'


class InputContextName(
    RootModel[constr(pattern=r'^([A-Za-z]_?)+$', min_length=1, max_length=100)]
):
    root: constr(pattern=r'^([A-Za-z]_?)+$', min_length=1, max_length=100)


class IntentName(
    RootModel[constr(pattern=r'^([A-Za-z]_?)+$', min_length=1, max_length=100)]
):
    root: constr(pattern=r'^([A-Za-z]_?)+$', min_length=1, max_length=100)


class InternalFailureException(RootModel[Any]):
    root: Any


class KendraIndexArn(
    RootModel[
        constr(
            pattern=r'arn:aws:kendra:[a-z]+-[a-z]+-[0-9]:[0-9]{12}:index\/[a-zA-Z0-9][a-zA-Z0-9_-]*',
            min_length=20,
            max_length=2048,
        )
    ]
):
    root: constr(
        pattern=r'arn:aws:kendra:[a-z]+-[a-z]+-[0-9]:[0-9]{12}:index\/[a-zA-Z0-9][a-zA-Z0-9_-]*',
        min_length=20,
        max_length=2048,
    )


class KmsKeyArn(
    RootModel[
        constr(
            pattern=r'^arn:[\w\-]+:kms:[\w\-]+:[\d]{12}:(?:key\/[\w\-]+|alias\/[a-zA-Z0-9:\/_\-]{1,256})$',
            min_length=20,
            max_length=2048,
        )
    ]
):
    root: constr(
        pattern=r'^arn:[\w\-]+:kms:[\w\-]+:[\d]{12}:(?:key\/[\w\-]+|alias\/[a-zA-Z0-9:\/_\-]{1,256})$',
        min_length=20,
        max_length=2048,
    )


class LambdaARN(
    RootModel[
        constr(
            pattern=r'arn:aws[a-zA-Z-]*:lambda:[a-z]+-[a-z]+(-[a-z]+)*-[0-9]:[0-9]{12}:function:[a-zA-Z0-9-_]+(\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})?(:[a-zA-Z0-9-_]+)?',
            min_length=20,
            max_length=2048,
        )
    ]
):
    root: constr(
        pattern=r'arn:aws[a-zA-Z-]*:lambda:[a-z]+-[a-z]+(-[a-z]+)*-[0-9]:[0-9]{12}:function:[a-zA-Z0-9-_]+(\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})?(:[a-zA-Z0-9-_]+)?',
        min_length=20,
        max_length=2048,
    )


class LimitExceededException(RootModel[Any]):
    root: Any


class ListTagsForResourceRequest(BaseModel):
    pass


class Locale(Enum):
    de_DE = 'de-DE'
    en_AU = 'en-AU'
    en_GB = 'en-GB'
    en_IN = 'en-IN'
    en_US = 'en-US'
    es_419 = 'es-419'
    es_ES = 'es-ES'
    es_US = 'es-US'
    fr_FR = 'fr-FR'
    fr_CA = 'fr-CA'
    it_IT = 'it-IT'
    ja_JP = 'ja-JP'
    ko_KR = 'ko-KR'


class LocaleList(RootModel[List[Locale]]):
    root: List[Locale]


class LogType(Enum):
    AUDIO = 'AUDIO'
    TEXT = 'TEXT'


class MaxResults(RootModel[conint(ge=1, le=50)]):
    root: conint(ge=1, le=50)


class MergeStrategy(Enum):
    OVERWRITE_LATEST = 'OVERWRITE_LATEST'
    FAIL_ON_CONFLICT = 'FAIL_ON_CONFLICT'


class Message(BaseModel):
    content: ContentString
    contentType: ContentType
    groupNumber: Optional[GroupNumber] = None


class MessageList(RootModel[List[Message]]):
    root: List[Message] = Field(..., max_length=15, min_length=1)


class MessageVersion(RootModel[constr(min_length=1, max_length=5)]):
    root: constr(min_length=1, max_length=5)


class MigrationAlertDetail(RootModel[str]):
    root: str


class MigrationAlertDetails(RootModel[List[MigrationAlertDetail]]):
    root: List[MigrationAlertDetail]


class MigrationAlertMessage(RootModel[str]):
    root: str


class MigrationAlertReferenceURL(RootModel[str]):
    root: str


class MigrationAlertReferenceURLs(RootModel[List[MigrationAlertReferenceURL]]):
    root: List[MigrationAlertReferenceURL]


class MigrationAlertType(Enum):
    ERROR = 'ERROR'
    WARN = 'WARN'


class MigrationId(
    RootModel[constr(pattern=r'^[0-9a-zA-Z]+$', min_length=10, max_length=10)]
):
    root: constr(pattern=r'^[0-9a-zA-Z]+$', min_length=10, max_length=10)


class MigrationSortAttribute(Enum):
    V1_BOT_NAME = 'V1_BOT_NAME'
    MIGRATION_DATE_TIME = 'MIGRATION_DATE_TIME'


class MigrationStatus(Enum):
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'


class MigrationStrategy(Enum):
    CREATE_NEW = 'CREATE_NEW'
    UPDATE_EXISTING = 'UPDATE_EXISTING'


class Name(RootModel[constr(pattern=r'[a-zA-Z_]+', min_length=1, max_length=100)]):
    root: constr(pattern=r'[a-zA-Z_]+', min_length=1, max_length=100)


class NextToken(RootModel[str]):
    root: str


class NotFoundException(RootModel[Any]):
    root: Any


class NumericalVersion(
    RootModel[constr(pattern=r'[0-9]+', min_length=1, max_length=64)]
):
    root: constr(pattern=r'[0-9]+', min_length=1, max_length=64)


class ObfuscationSetting(Enum):
    NONE = 'NONE'
    DEFAULT_OBFUSCATION = 'DEFAULT_OBFUSCATION'


class OutputContextName(
    RootModel[constr(pattern=r'^([A-Za-z]_?)+$', min_length=1, max_length=100)]
):
    root: constr(pattern=r'^([A-Za-z]_?)+$', min_length=1, max_length=100)


class PreconditionFailedException(RootModel[Any]):
    root: Any


class Priority(RootModel[conint(ge=0, le=100)]):
    root: conint(ge=0, le=100)


class ProcessBehavior(Enum):
    SAVE = 'SAVE'
    BUILD = 'BUILD'


class PromptMaxAttempts(RootModel[conint(ge=1, le=5)]):
    root: conint(ge=1, le=5)


class QueryFilterString(RootModel[constr(min_length=0)]):
    root: constr(min_length=0)


class RegexPattern(RootModel[constr(min_length=1, max_length=100)]):
    root: constr(min_length=1, max_length=100)


class ResourceArn(
    RootModel[
        constr(
            pattern=r'^arn:[\w\-]+:(?:logs:[\w\-]+:[\d]{12}:log-group:[\.\-_/#A-Za-z0-9]{1,512}(?::\*)?|s3:::[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9])$',
            min_length=1,
            max_length=2048,
        )
    ]
):
    root: constr(
        pattern=r'^arn:[\w\-]+:(?:logs:[\w\-]+:[\d]{12}:log-group:[\.\-_/#A-Za-z0-9]{1,512}(?::\*)?|s3:::[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9])$',
        min_length=1,
        max_length=2048,
    )


class ResourceInUseException(RootModel[Any]):
    root: Any


class ResourcePrefix(RootModel[constr(max_length=1024)]):
    root: constr(max_length=1024)


class ResourceType(Enum):
    BOT = 'BOT'
    INTENT = 'INTENT'
    SLOT_TYPE = 'SLOT_TYPE'


class ResponseCard(RootModel[constr(min_length=1, max_length=50000)]):
    root: constr(min_length=1, max_length=50000)


class SessionTTL(RootModel[conint(ge=60, le=86400)]):
    root: conint(ge=60, le=86400)


class SlotConstraint(Enum):
    Required = 'Required'
    Optional = 'Optional'


class SlotDefaultValueString(RootModel[constr(min_length=1, max_length=202)]):
    root: constr(min_length=1, max_length=202)


class SlotName(
    RootModel[constr(pattern=r'^([A-Za-z](-|_|.)?)+$', min_length=1, max_length=100)]
):
    root: constr(pattern=r'^([A-Za-z](-|_|.)?)+$', min_length=1, max_length=100)


class SlotTypeName(
    RootModel[constr(pattern=r'^([A-Za-z]_?)+$', min_length=1, max_length=100)]
):
    root: constr(pattern=r'^([A-Za-z]_?)+$', min_length=1, max_length=100)


class SlotTypeRegexConfiguration(BaseModel):
    pattern: RegexPattern


class SlotValueSelectionStrategy(Enum):
    ORIGINAL_VALUE = 'ORIGINAL_VALUE'
    TOP_RESOLUTION = 'TOP_RESOLUTION'


class SortOrder(Enum):
    ASCENDING = 'ASCENDING'
    DESCENDING = 'DESCENDING'


class Statement(BaseModel):
    messages: MessageList
    responseCard: Optional[ResponseCard] = None


class Status(Enum):
    BUILDING = 'BUILDING'
    READY = 'READY'
    READY_BASIC_TESTING = 'READY_BASIC_TESTING'
    FAILED = 'FAILED'
    NOT_BUILT = 'NOT_BUILT'


class StatusType(Enum):
    Detected = 'Detected'
    Missed = 'Missed'


class String(RootModel[str]):
    root: str


class StringList(RootModel[List[String]]):
    root: List[String]


class TagKey(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class TagKeyList(RootModel[List[TagKey]]):
    root: List[TagKey] = Field(..., max_length=200, min_length=0)


class TagResourceResponse(BaseModel):
    pass


class TagValue(RootModel[constr(min_length=0, max_length=256)]):
    root: constr(min_length=0, max_length=256)


class Timestamp(RootModel[datetime]):
    root: datetime


class UntagResourceRequest(BaseModel):
    pass


class UntagResourceResponse(BaseModel):
    pass


class UserId(RootModel[constr(min_length=2, max_length=100)]):
    root: constr(min_length=2, max_length=100)


class Utterance(RootModel[constr(min_length=1, max_length=200)]):
    root: constr(min_length=1, max_length=200)


class UtteranceString(RootModel[constr(min_length=1, max_length=2000)]):
    root: constr(min_length=1, max_length=2000)


class V2BotId(
    RootModel[constr(pattern=r'^[0-9a-zA-Z]+$', min_length=10, max_length=10)]
):
    root: constr(pattern=r'^[0-9a-zA-Z]+$', min_length=10, max_length=10)


class V2BotName(
    RootModel[constr(pattern=r'^([0-9a-zA-Z][_-]?)+$', min_length=1, max_length=100)]
):
    root: constr(pattern=r'^([0-9a-zA-Z][_-]?)+$', min_length=1, max_length=100)


class Value(RootModel[constr(min_length=1, max_length=140)]):
    root: constr(min_length=1, max_length=140)


class Version(
    RootModel[constr(pattern=r'\$LATEST|[0-9]+', min_length=1, max_length=64)]
):
    root: constr(pattern=r'\$LATEST|[0-9]+', min_length=1, max_length=64)


class RoleArn(
    RootModel[
        constr(
            pattern=r'arn:aws:iam::[0-9]{12}:role/.*', min_length=20, max_length=2048
        )
    ]
):
    root: constr(
        pattern=r'arn:aws:iam::[0-9]{12}:role/.*', min_length=20, max_length=2048
    )


class View(Enum):
    aggregation = 'aggregation'


class BotVersions(RootModel[List[Version]]):
    root: List[Version] = Field(..., max_length=5, min_length=1)


class BotsNameVersionsPostRequest(BaseModel):
    checksum: Optional[str] = Field(
        None,
        description="Identifies a specific revision of the <code>$LATEST</code> version of the bot. If you specify a checksum and the <code>$LATEST</code> version of the bot has a different checksum, a <code>PreconditionFailedException</code> exception is returned and Amazon Lex doesn't publish a new version. If you don't specify a checksum, Amazon Lex publishes the <code>$LATEST</code> version.",
    )


class AbortStatement(BaseModel):
    messages: Optional[MessageList] = None
    responseCard: Optional[ResponseCard] = None


class ClarificationPrompt(BaseModel):
    maxAttempts: Optional[PromptMaxAttempts] = None
    messages: Optional[MessageList] = None
    responseCard: Optional[ResponseCard] = None


class IntentsNameVersionsPostRequest(BaseModel):
    checksum: Optional[str] = Field(
        None,
        description="Checksum of the <code>$LATEST</code> version of the intent that should be used to create the new version. If you specify a checksum and the <code>$LATEST</code> version of the intent has a different checksum, Amazon Lex returns a <code>PreconditionFailedException</code> exception and doesn't publish a new version. If you don't specify a checksum, Amazon Lex publishes the <code>$LATEST</code> version.",
    )


class ConclusionStatement(BaseModel):
    messages: Optional[MessageList] = None
    responseCard: Optional[ResponseCard] = None


class ConfirmationPrompt(BaseModel):
    maxAttempts: Optional[PromptMaxAttempts] = None
    messages: Optional[MessageList] = None
    responseCard: Optional[ResponseCard] = None


class DialogCodeHook(BaseModel):
    messageVersion: Optional[MessageVersion] = None
    uri: Optional[LambdaARN] = None


class KendraConfiguration1(BaseModel):
    kendraIndex: Optional[KendraIndexArn] = None
    queryFilterString: Optional[QueryFilterString] = None
    role: Optional[RoleArn] = None


class RejectionStatement(BaseModel):
    messages: Optional[MessageList] = None
    responseCard: Optional[ResponseCard] = None


class SortByAttribute(Enum):
    V1_BOT_NAME = 'V1_BOT_NAME'
    MIGRATION_DATE_TIME = 'MIGRATION_DATE_TIME'


class SortByOrder(Enum):
    ASCENDING = 'ASCENDING'
    DESCENDING = 'DESCENDING'


class MigrationStatusEquals(Enum):
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'


class MigrationsPostRequest(BaseModel):
    migrationStrategy: MigrationStrategy = Field(
        ...,
        description="<p>The strategy used to conduct the migration.</p> <ul> <li> <p> <code>CREATE_NEW</code> - Creates a new Amazon Lex V2 bot and migrates the Amazon Lex V1 bot to the new bot.</p> </li> <li> <p> <code>UPDATE_EXISTING</code> - Overwrites the existing Amazon Lex V2 bot metadata and the locale being migrated. It doesn't change any other locales in the Amazon Lex V2 bot. If the locale doesn't exist, a new locale is created in the Amazon Lex V2 bot.</p> </li> </ul>",
    )
    v1BotName: constr(pattern=r'^([A-Za-z]_?)+$', min_length=2, max_length=50) = Field(
        ...,
        description='The name of the Amazon Lex V1 bot that you are migrating to Amazon Lex V2.',
    )
    v1BotVersion: constr(pattern=r'\$LATEST|[0-9]+', min_length=1, max_length=64) = (
        Field(
            ...,
            description='The version of the bot to migrate to Amazon Lex V2. You can migrate the <code>$LATEST</code> version as well as any numbered version.',
        )
    )
    v2BotName: constr(
        pattern=r'^([0-9a-zA-Z][_-]?)+$', min_length=1, max_length=100
    ) = Field(
        ...,
        description="<p>The name of the Amazon Lex V2 bot that you are migrating the Amazon Lex V1 bot to. </p> <ul> <li> <p>If the Amazon Lex V2 bot doesn't exist, you must use the <code>CREATE_NEW</code> migration strategy.</p> </li> <li> <p>If the Amazon Lex V2 bot exists, you must use the <code>UPDATE_EXISTING</code> migration strategy to change the contents of the Amazon Lex V2 bot.</p> </li> </ul>",
    )
    v2BotRole: constr(
        pattern=r'^arn:[\w\-]+:iam::[\d]{12}:role/.+$', min_length=20, max_length=2048
    ) = Field(
        ...,
        description='The IAM role that Amazon Lex uses to run the Amazon Lex V2 bot.',
    )


class SlottypesNameVersionsPostRequest(BaseModel):
    checksum: Optional[str] = Field(
        None,
        description="Checksum for the <code>$LATEST</code> version of the slot type that you want to publish. If you specify a checksum and the <code>$LATEST</code> version of the slot type has a different checksum, Amazon Lex returns a <code>PreconditionFailedException</code> exception and doesn't publish the new version. If you don't specify a checksum, Amazon Lex publishes the <code>$LATEST</code> version.",
    )


class ValueSelectionStrategy(Enum):
    ORIGINAL_VALUE = 'ORIGINAL_VALUE'
    TOP_RESOLUTION = 'TOP_RESOLUTION'


class TagKeys(RootModel[List[TagKey]]):
    root: List[TagKey] = Field(..., max_length=200, min_length=0)


class BotMetadata(BaseModel):
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    lastUpdatedDate: Optional[Timestamp] = None
    name: Optional[BotName] = None
    status: Optional[Status] = None
    version: Optional[Version] = None


class BotMetadataList(RootModel[List[BotMetadata]]):
    root: List[BotMetadata]


class BuiltinIntentMetadata(BaseModel):
    signature: Optional[BuiltinIntentSignature] = None
    supportedLocales: Optional[LocaleList] = None


class BuiltinIntentMetadataList(RootModel[List[BuiltinIntentMetadata]]):
    root: List[BuiltinIntentMetadata]


class BuiltinIntentSlot(BaseModel):
    name: Optional[String] = None


class BuiltinIntentSlotList(RootModel[List[BuiltinIntentSlot]]):
    root: List[BuiltinIntentSlot]


class BuiltinSlotTypeMetadata(BaseModel):
    signature: Optional[BuiltinSlotTypeSignature] = None
    supportedLocales: Optional[LocaleList] = None


class BuiltinSlotTypeMetadataList(RootModel[List[BuiltinSlotTypeMetadata]]):
    root: List[BuiltinSlotTypeMetadata]


class ChannelConfigurationMap(RootModel[Optional[Dict[str, String]]]):
    root: Optional[Dict[str, String]] = None


class CodeHook(BaseModel):
    messageVersion: MessageVersion
    uri: LambdaARN


class CreateBotVersionRequest(BaseModel):
    checksum: Optional[String] = None


class CreateIntentVersionRequest(BaseModel):
    checksum: Optional[String] = None


class CreateSlotTypeVersionRequest(BaseModel):
    checksum: Optional[String] = None


class FulfillmentActivity(BaseModel):
    codeHook: Optional[CodeHook] = None
    type: FulfillmentActivityType


class GetBotChannelAssociationResponse(BaseModel):
    botAlias: Optional[AliasName] = None
    botConfiguration: Optional[ChannelConfigurationMap] = None
    botName: Optional[BotName] = None
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    failureReason: Optional[String] = None
    name: Optional[BotChannelName] = None
    status: Optional[ChannelStatus] = None
    type: Optional[ChannelType] = None


class GetBotVersionsResponse(BaseModel):
    bots: Optional[BotMetadataList] = None
    nextToken: Optional[NextToken] = None


class GetBotsResponse(BaseModel):
    bots: Optional[BotMetadataList] = None
    nextToken: Optional[NextToken] = None


class GetBuiltinIntentResponse(BaseModel):
    signature: Optional[BuiltinIntentSignature] = None
    slots: Optional[BuiltinIntentSlotList] = None
    supportedLocales: Optional[LocaleList] = None


class GetBuiltinIntentsResponse(BaseModel):
    intents: Optional[BuiltinIntentMetadataList] = None
    nextToken: Optional[NextToken] = None


class GetBuiltinSlotTypesResponse(BaseModel):
    nextToken: Optional[NextToken] = None
    slotTypes: Optional[BuiltinSlotTypeMetadataList] = None


class GetExportResponse(BaseModel):
    exportStatus: Optional[ExportStatus] = None
    exportType: Optional[ExportType] = None
    failureReason: Optional[String] = None
    name: Optional[Name] = None
    resourceType: Optional[ResourceType] = None
    url: Optional[String] = None
    version: Optional[NumericalVersion] = None


class GetImportResponse(BaseModel):
    createdDate: Optional[Timestamp] = None
    failureReason: Optional[StringList] = None
    importId: Optional[String] = None
    importStatus: Optional[ImportStatus] = None
    mergeStrategy: Optional[MergeStrategy] = None
    name: Optional[Name] = None
    resourceType: Optional[ResourceType] = None


class InputContext(BaseModel):
    name: InputContextName


class InputContextList(RootModel[List[InputContext]]):
    root: List[InputContext] = Field(..., max_length=5, min_length=0)


class Intent(BaseModel):
    intentName: IntentName
    intentVersion: Version


class IntentList(RootModel[List[Intent]]):
    root: List[Intent]


class IntentMetadata(BaseModel):
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    lastUpdatedDate: Optional[Timestamp] = None
    name: Optional[IntentName] = None
    version: Optional[Version] = None


class IntentMetadataList(RootModel[List[IntentMetadata]]):
    root: List[IntentMetadata]


class IntentUtteranceList(RootModel[List[Utterance]]):
    root: List[Utterance] = Field(..., max_length=1500, min_length=0)


class KendraConfiguration(BaseModel):
    kendraIndex: KendraIndexArn
    queryFilterString: Optional[QueryFilterString] = None
    role: RoleArn


class LogSettingsRequest(BaseModel):
    destination: Destination
    kmsKeyArn: Optional[KmsKeyArn] = None
    logType: LogType
    resourceArn: ResourceArn


class LogSettingsRequestList(RootModel[List[LogSettingsRequest]]):
    root: List[LogSettingsRequest]


class LogSettingsResponse(BaseModel):
    destination: Optional[Destination] = None
    kmsKeyArn: Optional[KmsKeyArn] = None
    logType: Optional[LogType] = None
    resourceArn: Optional[ResourceArn] = None
    resourcePrefix: Optional[ResourcePrefix] = None


class LogSettingsResponseList(RootModel[List[LogSettingsResponse]]):
    root: List[LogSettingsResponse]


class MigrationAlert(BaseModel):
    details: Optional[MigrationAlertDetails] = None
    message: Optional[MigrationAlertMessage] = None
    referenceURLs: Optional[MigrationAlertReferenceURLs] = None
    type: Optional[MigrationAlertType] = None


class MigrationAlerts(RootModel[List[MigrationAlert]]):
    root: List[MigrationAlert]


class MigrationSummary(BaseModel):
    migrationId: Optional[MigrationId] = None
    migrationStatus: Optional[MigrationStatus] = None
    migrationStrategy: Optional[MigrationStrategy] = None
    migrationTimestamp: Optional[Timestamp] = None
    v1BotLocale: Optional[Locale] = None
    v1BotName: Optional[BotName] = None
    v1BotVersion: Optional[Version] = None
    v2BotId: Optional[V2BotId] = None
    v2BotRole: Optional[IamRoleArn] = None


class MigrationSummaryList(RootModel[List[MigrationSummary]]):
    root: List[MigrationSummary]


class OutputContext(BaseModel):
    name: OutputContextName
    timeToLiveInSeconds: ContextTimeToLiveInSeconds
    turnsToLive: ContextTurnsToLive


class OutputContextList(RootModel[List[OutputContext]]):
    root: List[OutputContext] = Field(..., max_length=10, min_length=0)


class Prompt(BaseModel):
    maxAttempts: PromptMaxAttempts
    messages: MessageList
    responseCard: Optional[ResponseCard] = None


class SlotDefaultValue(BaseModel):
    defaultValue: SlotDefaultValueString


class SlotDefaultValueList(RootModel[List[SlotDefaultValue]]):
    root: List[SlotDefaultValue] = Field(..., max_length=10, min_length=0)


class SlotDefaultValueSpec(BaseModel):
    defaultValueList: SlotDefaultValueList


class SlotTypeConfiguration(BaseModel):
    regexConfiguration: Optional[SlotTypeRegexConfiguration] = None


class SlotTypeConfigurations(RootModel[List[SlotTypeConfiguration]]):
    root: List[SlotTypeConfiguration] = Field(..., max_length=10, min_length=0)


class SlotTypeMetadata(BaseModel):
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    lastUpdatedDate: Optional[Timestamp] = None
    name: Optional[SlotTypeName] = None
    version: Optional[Version] = None


class SlotTypeMetadataList(RootModel[List[SlotTypeMetadata]]):
    root: List[SlotTypeMetadata]


class SlotUtteranceList(RootModel[List[Utterance]]):
    root: List[Utterance] = Field(..., max_length=10, min_length=0)


class StartMigrationRequest(BaseModel):
    migrationStrategy: MigrationStrategy
    v1BotName: BotName
    v1BotVersion: Version
    v2BotName: V2BotName
    v2BotRole: IamRoleArn


class StartMigrationResponse(BaseModel):
    migrationId: Optional[MigrationId] = None
    migrationStrategy: Optional[MigrationStrategy] = None
    migrationTimestamp: Optional[Timestamp] = None
    v1BotLocale: Optional[Locale] = None
    v1BotName: Optional[BotName] = None
    v1BotVersion: Optional[Version] = None
    v2BotId: Optional[V2BotId] = None
    v2BotRole: Optional[IamRoleArn] = None


class SynonymList(RootModel[List[Value]]):
    root: List[Value]


class Tag(BaseModel):
    key: TagKey
    value: TagValue


class TagList(RootModel[List[Tag]]):
    root: List[Tag] = Field(..., max_length=200, min_length=0)


class TagResourceRequest(BaseModel):
    tags: TagList


class UtteranceData(BaseModel):
    count: Optional[Count] = None
    distinctUsers: Optional[Count] = None
    firstUtteredDate: Optional[Timestamp] = None
    lastUtteredDate: Optional[Timestamp] = None
    utteranceString: Optional[UtteranceString] = None


class ConversationLogs(BaseModel):
    iamRoleArn: Optional[IamRoleArn] = None
    logSettings: Optional[LogSettingsRequestList] = None


class BotsBotNameAliasesNamePutRequest(BaseModel):
    botVersion: constr(pattern=r'\$LATEST|[0-9]+', min_length=1, max_length=64) = Field(
        ..., description='The version of the bot.'
    )
    checksum: Optional[str] = Field(
        None,
        description="<p>Identifies a specific revision of the <code>$LATEST</code> version.</p> <p>When you create a new bot alias, leave the <code>checksum</code> field blank. If you specify a checksum you get a <code>BadRequestException</code> exception.</p> <p>When you want to update a bot alias, set the <code>checksum</code> field to the checksum of the most recent revision of the <code>$LATEST</code> version. If you don't specify the <code> checksum</code> field, or if the checksum does not match the <code>$LATEST</code> version, you get a <code>PreconditionFailedException</code> exception.</p>",
    )
    conversationLogs: Optional[ConversationLogs] = Field(
        None, description='Provides the settings needed for conversation logs.'
    )
    description: Optional[constr(min_length=0, max_length=200)] = Field(
        None, description='A description of the alias.'
    )
    tags: Optional[List[Tag]] = Field(
        None,
        description="A list of tags to add to the bot alias. You can only add tags when you create an alias, you can't use the <code>PutBotAlias</code> operation to update the tags on a bot alias. To update tags, use the <code>TagResource</code> operation.",
        max_length=200,
        min_length=0,
    )


class BotsNameVersionsLATESTPutRequest(BaseModel):
    abortStatement: Optional[AbortStatement] = Field(
        None,
        description='A collection of messages that convey information to the user. At runtime, Amazon Lex selects the message to convey. ',
    )
    checksum: Optional[str] = Field(
        None,
        description="<p>Identifies a specific revision of the <code>$LATEST</code> version.</p> <p>When you create a new bot, leave the <code>checksum</code> field blank. If you specify a checksum you get a <code>BadRequestException</code> exception.</p> <p>When you want to update a bot, set the <code>checksum</code> field to the checksum of the most recent revision of the <code>$LATEST</code> version. If you don't specify the <code> checksum</code> field, or if the checksum does not match the <code>$LATEST</code> version, you get a <code>PreconditionFailedException</code> exception.</p>",
    )
    childDirected: bool = Field(
        ...,
        description='<p>For each Amazon Lex bot created with the Amazon Lex Model Building Service, you must specify whether your use of Amazon Lex is related to a website, program, or other application that is directed or targeted, in whole or in part, to children under age 13 and subject to the Children\'s Online Privacy Protection Act (COPPA) by specifying <code>true</code> or <code>false</code> in the <code>childDirected</code> field. By specifying <code>true</code> in the <code>childDirected</code> field, you confirm that your use of Amazon Lex <b>is</b> related to a website, program, or other application that is directed or targeted, in whole or in part, to children under age 13 and subject to COPPA. By specifying <code>false</code> in the <code>childDirected</code> field, you confirm that your use of Amazon Lex <b>is not</b> related to a website, program, or other application that is directed or targeted, in whole or in part, to children under age 13 and subject to COPPA. You may not specify a default value for the <code>childDirected</code> field that does not accurately reflect whether your use of Amazon Lex is related to a website, program, or other application that is directed or targeted, in whole or in part, to children under age 13 and subject to COPPA.</p> <p>If your use of Amazon Lex relates to a website, program, or other application that is directed in whole or in part, to children under age 13, you must obtain any required verifiable parental consent under COPPA. For information regarding the use of Amazon Lex in connection with websites, programs, or other applications that are directed or targeted, in whole or in part, to children under age 13, see the <a href="https://aws.amazon.com/lex/faqs#data-security">Amazon Lex FAQ.</a> </p>',
    )
    clarificationPrompt: Optional[ClarificationPrompt] = Field(
        None,
        description='Obtains information from the user. To define a prompt, provide one or more messages and specify the number of attempts to get information from the user. If you provide more than one message, Amazon Lex chooses one of the messages to use to prompt the user. For more information, see <a>how-it-works</a>.',
    )
    createVersion: Optional[bool] = Field(
        None,
        description="When set to <code>true</code> a new numbered version of the bot is created. This is the same as calling the <code>CreateBotVersion</code> operation. If you don't specify <code>createVersion</code>, the default is <code>false</code>.",
    )
    description: Optional[constr(min_length=0, max_length=200)] = Field(
        None, description='A description of the bot.'
    )
    detectSentiment: Optional[bool] = Field(
        None,
        description="When set to <code>true</code> user utterances are sent to Amazon Comprehend for sentiment analysis. If you don't specify <code>detectSentiment</code>, the default is <code>false</code>.",
    )
    enableModelImprovements: Optional[bool] = Field(
        None,
        description='<p>Set to <code>true</code> to enable access to natural language understanding improvements. </p> <p>When you set the <code>enableModelImprovements</code> parameter to <code>true</code> you can use the <code>nluIntentConfidenceThreshold</code> parameter to configure confidence scores. For more information, see <a href="https://docs.aws.amazon.com/lex/latest/dg/confidence-scores.html">Confidence Scores</a>.</p> <p>You can only set the <code>enableModelImprovements</code> parameter in certain Regions. If you set the parameter to <code>true</code>, your bot has access to accuracy improvements.</p> <p>The Regions where you can set the <code>enableModelImprovements</code> parameter to <code>true</code> are:</p> <ul> <li> <p>US East (N. Virginia) (us-east-1)</p> </li> <li> <p>US West (Oregon) (us-west-2)</p> </li> <li> <p>Asia Pacific (Sydney) (ap-southeast-2)</p> </li> <li> <p>EU (Ireland) (eu-west-1)</p> </li> </ul> <p>In other Regions, the <code>enableModelImprovements</code> parameter is set to <code>true</code> by default. In these Regions setting the parameter to <code>false</code> throws a <code>ValidationException</code> exception.</p>',
    )
    idleSessionTTLInSeconds: Optional[conint(ge=60, le=86400)] = Field(
        None,
        description="<p>The maximum time in seconds that Amazon Lex retains the data gathered in a conversation.</p> <p>A user interaction session remains active for the amount of time specified. If no conversation occurs during this time, the session expires and Amazon Lex deletes any data provided before the timeout.</p> <p>For example, suppose that a user chooses the OrderPizza intent, but gets sidetracked halfway through placing an order. If the user doesn't complete the order within the specified time, Amazon Lex discards the slot information that it gathered, and the user must start over.</p> <p>If you don't include the <code>idleSessionTTLInSeconds</code> element in a <code>PutBot</code> operation request, Amazon Lex uses the default value. This is also true if the request replaces an existing bot.</p> <p>The default is 300 seconds (5 minutes).</p>",
    )
    intents: Optional[List[Intent]] = Field(
        None,
        description='An array of <code>Intent</code> objects. Each intent represents a command that a user can express. For example, a pizza ordering bot might support an OrderPizza intent. For more information, see <a>how-it-works</a>.',
    )
    locale: Locale = Field(
        ...,
        description='<p> Specifies the target locale for the bot. Any intent used in the bot must be compatible with the locale of the bot. </p> <p>The default is <code>en-US</code>.</p>',
    )
    nluIntentConfidenceThreshold: Optional[confloat(ge=0.0, le=1.0)] = Field(
        None,
        description='<p>Determines the threshold where Amazon Lex will insert the <code>AMAZON.FallbackIntent</code>, <code>AMAZON.KendraSearchIntent</code>, or both when returning alternative intents in a <a href="https://docs.aws.amazon.com/lex/latest/dg/API_runtime_PostContent.html">PostContent</a> or <a href="https://docs.aws.amazon.com/lex/latest/dg/API_runtime_PostText.html">PostText</a> response. <code>AMAZON.FallbackIntent</code> and <code>AMAZON.KendraSearchIntent</code> are only inserted if they are configured for the bot.</p> <p>You must set the <code>enableModelImprovements</code> parameter to <code>true</code> to use confidence scores in the following regions.</p> <ul> <li> <p>US East (N. Virginia) (us-east-1)</p> </li> <li> <p>US West (Oregon) (us-west-2)</p> </li> <li> <p>Asia Pacific (Sydney) (ap-southeast-2)</p> </li> <li> <p>EU (Ireland) (eu-west-1)</p> </li> </ul> <p>In other Regions, the <code>enableModelImprovements</code> parameter is set to <code>true</code> by default.</p> <p>For example, suppose a bot is configured with the confidence threshold of 0.80 and the <code>AMAZON.FallbackIntent</code>. Amazon Lex returns three alternative intents with the following confidence scores: IntentA (0.70), IntentB (0.60), IntentC (0.50). The response from the <code>PostText</code> operation would be:</p> <ul> <li> <p>AMAZON.FallbackIntent</p> </li> <li> <p>IntentA</p> </li> <li> <p>IntentB</p> </li> <li> <p>IntentC</p> </li> </ul>',
    )
    processBehavior: Optional[ProcessBehavior] = Field(
        None,
        description="<p>If you set the <code>processBehavior</code> element to <code>BUILD</code>, Amazon Lex builds the bot so that it can be run. If you set the element to <code>SAVE</code> Amazon Lex saves the bot, but doesn't build it. </p> <p>If you don't specify this value, the default value is <code>BUILD</code>.</p>",
    )
    tags: Optional[List[Tag]] = Field(
        None,
        description="A list of tags to add to the bot. You can only add tags when you create a bot, you can't use the <code>PutBot</code> operation to update the tags on a bot. To update tags, use the <code>TagResource</code> operation.",
        max_length=200,
        min_length=0,
    )
    voiceId: Optional[str] = Field(
        None,
        description='The Amazon Polly voice ID that you want Amazon Lex to use for voice interactions with the user. The locale configured for the voice must match the locale of the bot. For more information, see <a href="https://docs.aws.amazon.com/polly/latest/dg/voicelist.html">Voices in Amazon Polly</a> in the <i>Amazon Polly Developer Guide</i>.',
    )


class ImportsPostRequest(BaseModel):
    mergeStrategy: MergeStrategy = Field(
        ...,
        description='<p>Specifies the action that the <code>StartImport</code> operation should take when there is an existing resource with the same name.</p> <ul> <li> <p>FAIL_ON_CONFLICT - The import operation is stopped on the first conflict between a resource in the import file and an existing resource. The name of the resource causing the conflict is in the <code>failureReason</code> field of the response to the <code>GetImport</code> operation.</p> <p>OVERWRITE_LATEST - The import operation proceeds even if there is a conflict with an existing resource. The $LASTEST version of the existing resource is overwritten with the data from the import file.</p> </li> </ul>',
    )
    payload: str = Field(
        ...,
        description='A zip archive in binary format. The archive should contain one file, a JSON file containing the resource to import. The resource should match the type specified in the <code>resourceType</code> field.',
    )
    resourceType: ResourceType = Field(
        ...,
        description='<p>Specifies the type of resource to export. Each resource also exports any resources that it depends on. </p> <ul> <li> <p>A bot exports dependent intents.</p> </li> <li> <p>An intent exports dependent slot types.</p> </li> </ul>',
    )
    tags: Optional[List[Tag]] = Field(
        None,
        description="A list of tags to add to the imported bot. You can only add tags when you import a bot, you can't add tags to an intent or slot type.",
        max_length=200,
        min_length=0,
    )


class FollowUpPrompt1(BaseModel):
    prompt: Optional[Prompt] = None
    rejectionStatement: Optional[Statement] = None


class FulfillmentActivity1(BaseModel):
    codeHook: Optional[CodeHook] = None
    type: Optional[FulfillmentActivityType] = None


class TagsResourceArnPostRequest(BaseModel):
    tags: List[Tag] = Field(
        ...,
        description='A list of tag keys to add to the resource. If a tag key already exists, the existing value is replaced with the new value.',
        max_length=200,
        min_length=0,
    )


class BotChannelAssociation(BaseModel):
    botAlias: Optional[AliasName] = None
    botConfiguration: Optional[ChannelConfigurationMap] = None
    botName: Optional[BotName] = None
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    failureReason: Optional[String] = None
    name: Optional[BotChannelName] = None
    status: Optional[ChannelStatus] = None
    type: Optional[ChannelType] = None


class BotChannelAssociationList(RootModel[List[BotChannelAssociation]]):
    root: List[BotChannelAssociation]


class ConversationLogsRequest(BaseModel):
    iamRoleArn: IamRoleArn
    logSettings: LogSettingsRequestList


class ConversationLogsResponse(BaseModel):
    iamRoleArn: Optional[IamRoleArn] = None
    logSettings: Optional[LogSettingsResponseList] = None


class CreateBotVersionResponse(BaseModel):
    abortStatement: Optional[Statement] = None
    checksum: Optional[String] = None
    childDirected: Optional[Boolean] = None
    clarificationPrompt: Optional[Prompt] = None
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    detectSentiment: Optional[Boolean] = None
    enableModelImprovements: Optional[Boolean] = None
    failureReason: Optional[String] = None
    idleSessionTTLInSeconds: Optional[SessionTTL] = None
    intents: Optional[IntentList] = None
    lastUpdatedDate: Optional[Timestamp] = None
    locale: Optional[Locale] = None
    name: Optional[BotName] = None
    status: Optional[Status] = None
    version: Optional[Version] = None
    voiceId: Optional[String] = None


class EnumerationValue(BaseModel):
    synonyms: Optional[SynonymList] = None
    value: Value


class EnumerationValues(RootModel[List[EnumerationValue]]):
    root: List[EnumerationValue] = Field(..., max_length=10000, min_length=0)


class FollowUpPrompt(BaseModel):
    prompt: Prompt
    rejectionStatement: Statement


class GetBotAliasResponse(BaseModel):
    botName: Optional[BotName] = None
    botVersion: Optional[Version] = None
    checksum: Optional[String] = None
    conversationLogs: Optional[ConversationLogsResponse] = None
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    lastUpdatedDate: Optional[Timestamp] = None
    name: Optional[AliasName] = None


class GetBotChannelAssociationsResponse(BaseModel):
    botChannelAssociations: Optional[BotChannelAssociationList] = None
    nextToken: Optional[NextToken] = None


class GetBotResponse(BaseModel):
    abortStatement: Optional[Statement] = None
    checksum: Optional[String] = None
    childDirected: Optional[Boolean] = None
    clarificationPrompt: Optional[Prompt] = None
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    detectSentiment: Optional[Boolean] = None
    enableModelImprovements: Optional[Boolean] = None
    failureReason: Optional[String] = None
    idleSessionTTLInSeconds: Optional[SessionTTL] = None
    intents: Optional[IntentList] = None
    lastUpdatedDate: Optional[Timestamp] = None
    locale: Optional[Locale] = None
    name: Optional[BotName] = None
    nluIntentConfidenceThreshold: Optional[ConfidenceThreshold] = None
    status: Optional[Status] = None
    version: Optional[Version] = None
    voiceId: Optional[String] = None


class GetIntentVersionsResponse(BaseModel):
    intents: Optional[IntentMetadataList] = None
    nextToken: Optional[NextToken] = None


class GetIntentsResponse(BaseModel):
    intents: Optional[IntentMetadataList] = None
    nextToken: Optional[NextToken] = None


class GetMigrationResponse(BaseModel):
    alerts: Optional[MigrationAlerts] = None
    migrationId: Optional[MigrationId] = None
    migrationStatus: Optional[MigrationStatus] = None
    migrationStrategy: Optional[MigrationStrategy] = None
    migrationTimestamp: Optional[Timestamp] = None
    v1BotLocale: Optional[Locale] = None
    v1BotName: Optional[BotName] = None
    v1BotVersion: Optional[Version] = None
    v2BotId: Optional[V2BotId] = None
    v2BotRole: Optional[IamRoleArn] = None


class GetMigrationsResponse(BaseModel):
    migrationSummaries: Optional[MigrationSummaryList] = None
    nextToken: Optional[NextToken] = None


class GetSlotTypeResponse(BaseModel):
    checksum: Optional[String] = None
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    enumerationValues: Optional[EnumerationValues] = None
    lastUpdatedDate: Optional[Timestamp] = None
    name: Optional[SlotTypeName] = None
    parentSlotTypeSignature: Optional[CustomOrBuiltinSlotTypeName] = None
    slotTypeConfigurations: Optional[SlotTypeConfigurations] = None
    valueSelectionStrategy: Optional[SlotValueSelectionStrategy] = None
    version: Optional[Version] = None


class GetSlotTypeVersionsResponse(BaseModel):
    nextToken: Optional[NextToken] = None
    slotTypes: Optional[SlotTypeMetadataList] = None


class GetSlotTypesResponse(BaseModel):
    nextToken: Optional[NextToken] = None
    slotTypes: Optional[SlotTypeMetadataList] = None


class ListOfUtterance(RootModel[List[UtteranceData]]):
    root: List[UtteranceData]


class ListTagsForResourceResponse(BaseModel):
    tags: Optional[TagList] = None


class PutBotAliasRequest(BaseModel):
    botVersion: Version
    checksum: Optional[String] = None
    conversationLogs: Optional[ConversationLogsRequest] = None
    description: Optional[Description] = None
    tags: Optional[TagList] = None


class PutBotAliasResponse(BaseModel):
    botName: Optional[BotName] = None
    botVersion: Optional[Version] = None
    checksum: Optional[String] = None
    conversationLogs: Optional[ConversationLogsResponse] = None
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    lastUpdatedDate: Optional[Timestamp] = None
    name: Optional[AliasName] = None
    tags: Optional[TagList] = None


class PutBotRequest(BaseModel):
    abortStatement: Optional[Statement] = None
    checksum: Optional[String] = None
    childDirected: Boolean
    clarificationPrompt: Optional[Prompt] = None
    createVersion: Optional[Boolean] = None
    description: Optional[Description] = None
    detectSentiment: Optional[Boolean] = None
    enableModelImprovements: Optional[Boolean] = None
    idleSessionTTLInSeconds: Optional[SessionTTL] = None
    intents: Optional[IntentList] = None
    locale: Locale
    nluIntentConfidenceThreshold: Optional[ConfidenceThreshold] = None
    processBehavior: Optional[ProcessBehavior] = None
    tags: Optional[TagList] = None
    voiceId: Optional[String] = None


class PutBotResponse(BaseModel):
    abortStatement: Optional[Statement] = None
    checksum: Optional[String] = None
    childDirected: Optional[Boolean] = None
    clarificationPrompt: Optional[Prompt] = None
    createVersion: Optional[Boolean] = None
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    detectSentiment: Optional[Boolean] = None
    enableModelImprovements: Optional[Boolean] = None
    failureReason: Optional[String] = None
    idleSessionTTLInSeconds: Optional[SessionTTL] = None
    intents: Optional[IntentList] = None
    lastUpdatedDate: Optional[Timestamp] = None
    locale: Optional[Locale] = None
    name: Optional[BotName] = None
    nluIntentConfidenceThreshold: Optional[ConfidenceThreshold] = None
    status: Optional[Status] = None
    tags: Optional[TagList] = None
    version: Optional[Version] = None
    voiceId: Optional[String] = None


class PutSlotTypeRequest(BaseModel):
    checksum: Optional[String] = None
    createVersion: Optional[Boolean] = None
    description: Optional[Description] = None
    enumerationValues: Optional[EnumerationValues] = None
    parentSlotTypeSignature: Optional[CustomOrBuiltinSlotTypeName] = None
    slotTypeConfigurations: Optional[SlotTypeConfigurations] = None
    valueSelectionStrategy: Optional[SlotValueSelectionStrategy] = None


class PutSlotTypeResponse(BaseModel):
    checksum: Optional[String] = None
    createVersion: Optional[Boolean] = None
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    enumerationValues: Optional[EnumerationValues] = None
    lastUpdatedDate: Optional[Timestamp] = None
    name: Optional[SlotTypeName] = None
    parentSlotTypeSignature: Optional[CustomOrBuiltinSlotTypeName] = None
    slotTypeConfigurations: Optional[SlotTypeConfigurations] = None
    valueSelectionStrategy: Optional[SlotValueSelectionStrategy] = None
    version: Optional[Version] = None


class Slot(BaseModel):
    defaultValueSpec: Optional[SlotDefaultValueSpec] = None
    description: Optional[Description] = None
    name: SlotName
    obfuscationSetting: Optional[ObfuscationSetting] = None
    priority: Optional[Priority] = None
    responseCard: Optional[ResponseCard] = None
    sampleUtterances: Optional[SlotUtteranceList] = None
    slotConstraint: SlotConstraint
    slotType: Optional[CustomOrBuiltinSlotTypeName] = None
    slotTypeVersion: Optional[Version] = None
    valueElicitationPrompt: Optional[Prompt] = None


class SlotList(RootModel[List[Slot]]):
    root: List[Slot] = Field(..., max_length=100, min_length=0)


class StartImportRequest(BaseModel):
    mergeStrategy: MergeStrategy
    payload: Blob
    resourceType: ResourceType
    tags: Optional[TagList] = None


class StartImportResponse(BaseModel):
    createdDate: Optional[Timestamp] = None
    importId: Optional[String] = None
    importStatus: Optional[ImportStatus] = None
    mergeStrategy: Optional[MergeStrategy] = None
    name: Optional[Name] = None
    resourceType: Optional[ResourceType] = None
    tags: Optional[TagList] = None


class UtteranceList(BaseModel):
    botVersion: Optional[Version] = None
    utterances: Optional[ListOfUtterance] = None


class IntentsNameVersionsLATESTPutRequest(BaseModel):
    checksum: Optional[str] = Field(
        None,
        description="<p>Identifies a specific revision of the <code>$LATEST</code> version.</p> <p>When you create a new intent, leave the <code>checksum</code> field blank. If you specify a checksum you get a <code>BadRequestException</code> exception.</p> <p>When you want to update a intent, set the <code>checksum</code> field to the checksum of the most recent revision of the <code>$LATEST</code> version. If you don't specify the <code> checksum</code> field, or if the checksum does not match the <code>$LATEST</code> version, you get a <code>PreconditionFailedException</code> exception.</p>",
    )
    conclusionStatement: Optional[ConclusionStatement] = Field(
        None,
        description='A collection of messages that convey information to the user. At runtime, Amazon Lex selects the message to convey. ',
    )
    confirmationPrompt: Optional[ConfirmationPrompt] = Field(
        None,
        description='Obtains information from the user. To define a prompt, provide one or more messages and specify the number of attempts to get information from the user. If you provide more than one message, Amazon Lex chooses one of the messages to use to prompt the user. For more information, see <a>how-it-works</a>.',
    )
    createVersion: Optional[bool] = Field(
        None,
        description='When set to <code>true</code> a new numbered version of the intent is created. This is the same as calling the <code>CreateIntentVersion</code> operation. If you do not specify <code>createVersion</code>, the default is <code>false</code>.',
    )
    description: Optional[constr(min_length=0, max_length=200)] = Field(
        None, description='A description of the intent.'
    )
    dialogCodeHook: Optional[DialogCodeHook] = Field(
        None,
        description="Specifies a Lambda function that verifies requests to a bot or fulfills the user's request to a bot..",
    )
    followUpPrompt: Optional[FollowUpPrompt1] = Field(
        None,
        description='A prompt for additional activity after an intent is fulfilled. For example, after the <code>OrderPizza</code> intent is fulfilled, you might prompt the user to find out whether the user wants to order drinks.',
    )
    fulfillmentActivity: Optional[FulfillmentActivity1] = Field(
        None,
        description='<p> Describes how the intent is fulfilled after the user provides all of the information required for the intent. You can provide a Lambda function to process the intent, or you can return the intent information to the client application. We recommend that you use a Lambda function so that the relevant logic lives in the Cloud and limit the client-side code primarily to presentation. If you need to update the logic, you only update the Lambda function; you don\'t need to upgrade your client application. </p> <p>Consider the following examples:</p> <ul> <li> <p>In a pizza ordering application, after the user provides all of the information for placing an order, you use a Lambda function to place an order with a pizzeria. </p> </li> <li> <p>In a gaming application, when a user says "pick up a rock," this information must go back to the client application so that it can perform the operation and update the graphics. In this case, you want Amazon Lex to return the intent data to the client. </p> </li> </ul>',
    )
    inputContexts: Optional[List[InputContext]] = Field(
        None,
        description='An array of <code>InputContext</code> objects that lists the contexts that must be active for Amazon Lex to choose the intent in a conversation with the user.',
        max_length=5,
        min_length=0,
    )
    kendraConfiguration: Optional[KendraConfiguration1] = Field(
        None,
        description='Provides configuration information for the AMAZON.KendraSearchIntent intent. When you use this intent, Amazon Lex searches the specified Amazon Kendra index and returns documents from the index that match the user\'s utterance. For more information, see <a href="http://docs.aws.amazon.com/lex/latest/dg/built-in-intent-kendra-search.html"> AMAZON.KendraSearchIntent</a>.',
    )
    outputContexts: Optional[List[OutputContext]] = Field(
        None,
        description='An array of <code>OutputContext</code> objects that lists the contexts that the intent activates when the intent is fulfilled.',
        max_length=10,
        min_length=0,
    )
    parentIntentSignature: Optional[str] = Field(
        None,
        description='A unique identifier for the built-in intent to base this intent on. To find the signature for an intent, see <a href="https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/standard-intents">Standard Built-in Intents</a> in the <i>Alexa Skills Kit</i>.',
    )
    rejectionStatement: Optional[RejectionStatement] = Field(
        None,
        description='A collection of messages that convey information to the user. At runtime, Amazon Lex selects the message to convey. ',
    )
    sampleUtterances: Optional[List[Utterance]] = Field(
        None,
        description='<p>An array of utterances (strings) that a user might say to signal the intent. For example, "I want {PizzaSize} pizza", "Order {Quantity} {PizzaSize} pizzas". </p> <p>In each utterance, a slot name is enclosed in curly braces. </p>',
        max_length=1500,
        min_length=0,
    )
    slots: Optional[List[Slot]] = Field(
        None,
        description='An array of intent slots. At runtime, Amazon Lex elicits required slot values from the user using prompts defined in the slots. For more information, see <a>how-it-works</a>. ',
        max_length=100,
        min_length=0,
    )


class SlottypesNameVersionsLATESTPutRequest(BaseModel):
    checksum: Optional[str] = Field(
        None,
        description="<p>Identifies a specific revision of the <code>$LATEST</code> version.</p> <p>When you create a new slot type, leave the <code>checksum</code> field blank. If you specify a checksum you get a <code>BadRequestException</code> exception.</p> <p>When you want to update a slot type, set the <code>checksum</code> field to the checksum of the most recent revision of the <code>$LATEST</code> version. If you don't specify the <code> checksum</code> field, or if the checksum does not match the <code>$LATEST</code> version, you get a <code>PreconditionFailedException</code> exception.</p>",
    )
    createVersion: Optional[bool] = Field(
        None,
        description='When set to <code>true</code> a new numbered version of the slot type is created. This is the same as calling the <code>CreateSlotTypeVersion</code> operation. If you do not specify <code>createVersion</code>, the default is <code>false</code>.',
    )
    description: Optional[constr(min_length=0, max_length=200)] = Field(
        None, description='A description of the slot type.'
    )
    enumerationValues: Optional[List[EnumerationValue]] = Field(
        None,
        description="<p>A list of <code>EnumerationValue</code> objects that defines the values that the slot type can take. Each value can have a list of <code>synonyms</code>, which are additional values that help train the machine learning model about the values that it resolves for a slot. </p> <p>A regular expression slot type doesn't require enumeration values. All other slot types require a list of enumeration values.</p> <p>When Amazon Lex resolves a slot value, it generates a resolution list that contains up to five possible values for the slot. If you are using a Lambda function, this resolution list is passed to the function. If you are not using a Lambda function you can choose to return the value that the user entered or the first value in the resolution list as the slot value. The <code>valueSelectionStrategy</code> field indicates the option to use. </p>",
        max_length=10000,
        min_length=0,
    )
    parentSlotTypeSignature: Optional[
        constr(pattern=r'^((AMAZON\.)_?|[A-Za-z]_?)+', min_length=1, max_length=100)
    ] = Field(
        None,
        description='<p>The built-in slot type used as the parent of the slot type. When you define a parent slot type, the new slot type has all of the same configuration as the parent.</p> <p>Only <code>AMAZON.AlphaNumeric</code> is supported.</p>',
    )
    slotTypeConfigurations: Optional[List[SlotTypeConfiguration]] = Field(
        None,
        description='Configuration information that extends the parent built-in slot type. The configuration is added to the settings for the parent slot type.',
        max_length=10,
        min_length=0,
    )
    valueSelectionStrategy: Optional[ValueSelectionStrategy] = Field(
        None,
        description="<p>Determines the slot resolution strategy that Amazon Lex uses to return slot type values. The field can be set to one of the following values:</p> <ul> <li> <p> <code>ORIGINAL_VALUE</code> - Returns the value entered by the user, if the user value is similar to the slot value.</p> </li> <li> <p> <code>TOP_RESOLUTION</code> - If there is a resolution list for the slot, return the first value in the resolution list as the slot type value. If there is no resolution list, null is returned.</p> </li> </ul> <p>If you don't specify the <code>valueSelectionStrategy</code>, the default is <code>ORIGINAL_VALUE</code>.</p>",
    )


class BotAliasMetadata(BaseModel):
    botName: Optional[BotName] = None
    botVersion: Optional[Version] = None
    checksum: Optional[String] = None
    conversationLogs: Optional[ConversationLogsResponse] = None
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    lastUpdatedDate: Optional[Timestamp] = None
    name: Optional[AliasName] = None


class BotAliasMetadataList(RootModel[List[BotAliasMetadata]]):
    root: List[BotAliasMetadata]


class CreateIntentVersionResponse(BaseModel):
    checksum: Optional[String] = None
    conclusionStatement: Optional[Statement] = None
    confirmationPrompt: Optional[Prompt] = None
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    dialogCodeHook: Optional[CodeHook] = None
    followUpPrompt: Optional[FollowUpPrompt] = None
    fulfillmentActivity: Optional[FulfillmentActivity] = None
    inputContexts: Optional[InputContextList] = None
    kendraConfiguration: Optional[KendraConfiguration] = None
    lastUpdatedDate: Optional[Timestamp] = None
    name: Optional[IntentName] = None
    outputContexts: Optional[OutputContextList] = None
    parentIntentSignature: Optional[BuiltinIntentSignature] = None
    rejectionStatement: Optional[Statement] = None
    sampleUtterances: Optional[IntentUtteranceList] = None
    slots: Optional[SlotList] = None
    version: Optional[Version] = None


class CreateSlotTypeVersionResponse(BaseModel):
    checksum: Optional[String] = None
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    enumerationValues: Optional[EnumerationValues] = None
    lastUpdatedDate: Optional[Timestamp] = None
    name: Optional[SlotTypeName] = None
    parentSlotTypeSignature: Optional[CustomOrBuiltinSlotTypeName] = None
    slotTypeConfigurations: Optional[SlotTypeConfigurations] = None
    valueSelectionStrategy: Optional[SlotValueSelectionStrategy] = None
    version: Optional[Version] = None


class GetBotAliasesResponse(BaseModel):
    BotAliases: Optional[BotAliasMetadataList] = None
    nextToken: Optional[NextToken] = None


class GetIntentResponse(BaseModel):
    checksum: Optional[String] = None
    conclusionStatement: Optional[Statement] = None
    confirmationPrompt: Optional[Prompt] = None
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    dialogCodeHook: Optional[CodeHook] = None
    followUpPrompt: Optional[FollowUpPrompt] = None
    fulfillmentActivity: Optional[FulfillmentActivity] = None
    inputContexts: Optional[InputContextList] = None
    kendraConfiguration: Optional[KendraConfiguration] = None
    lastUpdatedDate: Optional[Timestamp] = None
    name: Optional[IntentName] = None
    outputContexts: Optional[OutputContextList] = None
    parentIntentSignature: Optional[BuiltinIntentSignature] = None
    rejectionStatement: Optional[Statement] = None
    sampleUtterances: Optional[IntentUtteranceList] = None
    slots: Optional[SlotList] = None
    version: Optional[Version] = None


class ListsOfUtterances(RootModel[List[UtteranceList]]):
    root: List[UtteranceList]


class PutIntentRequest(BaseModel):
    checksum: Optional[String] = None
    conclusionStatement: Optional[Statement] = None
    confirmationPrompt: Optional[Prompt] = None
    createVersion: Optional[Boolean] = None
    description: Optional[Description] = None
    dialogCodeHook: Optional[CodeHook] = None
    followUpPrompt: Optional[FollowUpPrompt] = None
    fulfillmentActivity: Optional[FulfillmentActivity] = None
    inputContexts: Optional[InputContextList] = None
    kendraConfiguration: Optional[KendraConfiguration] = None
    outputContexts: Optional[OutputContextList] = None
    parentIntentSignature: Optional[BuiltinIntentSignature] = None
    rejectionStatement: Optional[Statement] = None
    sampleUtterances: Optional[IntentUtteranceList] = None
    slots: Optional[SlotList] = None


class PutIntentResponse(BaseModel):
    checksum: Optional[String] = None
    conclusionStatement: Optional[Statement] = None
    confirmationPrompt: Optional[Prompt] = None
    createVersion: Optional[Boolean] = None
    createdDate: Optional[Timestamp] = None
    description: Optional[Description] = None
    dialogCodeHook: Optional[CodeHook] = None
    followUpPrompt: Optional[FollowUpPrompt] = None
    fulfillmentActivity: Optional[FulfillmentActivity] = None
    inputContexts: Optional[InputContextList] = None
    kendraConfiguration: Optional[KendraConfiguration] = None
    lastUpdatedDate: Optional[Timestamp] = None
    name: Optional[IntentName] = None
    outputContexts: Optional[OutputContextList] = None
    parentIntentSignature: Optional[BuiltinIntentSignature] = None
    rejectionStatement: Optional[Statement] = None
    sampleUtterances: Optional[IntentUtteranceList] = None
    slots: Optional[SlotList] = None
    version: Optional[Version] = None


class GetUtterancesViewResponse(BaseModel):
    botName: Optional[BotName] = None
    utterances: Optional[ListsOfUtterances] = None
